### ISSUE TITLE
Bugs in NWbib subject hierarchy 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#131]
Reported today by H.F. via mailinglist:

> wir sind in der Darstellung unserer Sachsystematik auf eine nicht 
> korrekte Hierarchie unter 523000 aufmerksam geworden:
> 
>   * Die Stelle 524000 ist der gleichgeordneten Stelle 523000
>     untergeordnet. Sie muss eine Stufe höher direkt unter 520000
> 
> Damit im Zusammenhang zu sehen ist:
> 
>   * Die Stelle 523001 ist an richtiger  hierarchischer Position, nicht
>     aber die ihr untergeordneten Stellen wie 523010 usw., welche auf
>     eine Stufe mit 523001 gehören.
> 
> Der Lapsus muss schon bei Einpflege der NWBib-Systematik in die 
> hbz-Katalogausgabe im Jahr 2007 nicht aufgefallen sein, denn auch dort 
> ist die Hierarchie nicht korrekt. Ältere Papierausgaben der NWBib 
> belegen das.
> 
> Nicht nur aus sachlicher Sicht, sondern auch wenn der Fehler bislang 
> nicht lautstark moniert wurde, schlage ich vor, ihn zu beheben. Denn wer 
> weiß, wievielen Nutzenden  524000 Sozialpädagogik beim Browsen schlicht 
> entgangen ist, da die Stelle nicht unter Sozialhilfe zu vermuten ist. 
> Ebenso gehören 523010 Arbeitslosenhilfe etc. unvermittelt und direkt 
> erreichbar unter 523000 Sozialhilfe (Fürsorge).
>

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/subjects#N520000
https://test.nwbib.de/subjects#N523000

**Comment by acka47** [comment]
+1 from me an H.F. Please deploy to production.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

https://nwbib.de/subjects#N520000
https://nwbib.de/subjects#N523000
