### ISSUE TITLE
Add "Keyword" class

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#133]

**Comment by acka47** [comment]
I can't remember where this is coming from. There is no typed "Keyword" in the [JSON-LD context for lobid-resources](http://lobid.org/resources/context.jsonld). Closing.

**Comment by TobiasNx** [comment]
If I remember correctly: Context was that we needed a type for subjects that are not part of any controlled vocabulary but are tags. I will have a look if we are still using it.
