### ISSUE TITLE
Clean up URIs for LBZ/RPB vocabs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#212]
Originates from https://github.com/acka47/scripts/pull/1#issuecomment-1947962420. Currently, we have these four vocabs from LBZ/RPB:

- `https://rpb.lobid.org/spatial#` for the relatively new Raumsystematik, which is available from https://rpb.lobid.org/spatial
- `http://purl.org/lobid/rpb#` for the Sachsystematik, which is available from https://rpb.lobid.org/subjects
- `https://w3id.org/lobid/rpb2` for the LBZ- notations that actually aren't used in RPB but in anothr LBZ context.
- `https://w3id.org/lobid/rpb-fachgebiete/` for the newly created RPB-Fachgebiete

My suggestions for improvements:

- [ ] use `https://rpb.lobid.org/subjects#` as namespace for Sachsystematik
- [ ] update namespace for LBZ-notations to  `https://w3id.org/lobid/lbz-notations/` (new name and slash instead of hash URIs)

Afterwards:

- [ ] Adjust the `.htaccess ` file at https://github.com/perma-id/w3id.org/blob/master/lobid/.htaccess to point the w3id vocabs to https://skohub.io/hbz/lobid-vocabs/heads/master/

**Comment by TobiasNx** [comment]
@acka47 is this still relevant?

**Comment by acka47** [comment]
We won't change any URIs that have been used for some time as we can neither estimate the effort for us to update applications nor know who else might be affected. Closing
