### ISSUE TITLE
Use RPB Spatial notation in SKOS

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-vocabs#228]
At the moment the SKOS notation for RPB Spatial is not used. Should we put them in the SKOS File too? To reduce the confusion in communication with LBZ.

To also document the difference between o and not o concepts in spatial?

```
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">rpbr_01_</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
```

=> https://rpb.lobid.org/spatial#n01

```
:n01 a skos:Concept ;
    skos:broader :n1 ;
    skos:closeMatch <http://d-nb.info/gnd/4049795-1> ;
    skos:definition "Rheinland-Pfalz insgesamt. Landesteile (n1) > Rheinland-Pfalz (n01)"@de ;
    skos:inScheme <https://rpb.lobid.org/spatial> ;
    skos:notation "01" ;
    skos:prefLabel "Rheinland-Pfalz"@de .

``


```
<datafield tag="084" ind1=" " ind2=" ">
  <subfield code="a">rpbr_99_o13802_</subfield>
  <subfield code="2">rpb</subfield>
</datafield>
```

=> https://rpb.lobid.org/spatial#n13802

```
:n13802 a skos:Concept ;
    skos:broader :n138 ;
    skos:definition "Einzelne Landkreise, Verbandsgemeinden, Orte und Ortsteile (n6) > Neuwied, Landkreis (n138) > Bad Hönningen, Verbandsgemeinde (n13802)"@de ;
    skos:inScheme <https://rpb.lobid.org/spatial> ;
    skos:notation "o13802" ;
    skos:prefLabel "Bad Hönningen, Verbandsgemeinde"@de .
```

**Comment by acka47** [comment]
Moved to https://github.com/hbz/lbz-vocabs/issues/1. Closing
