### ISSUE TITLE
Create lv:isPartOf and lv:superordinate

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#65]
See https://github.com/hbz/lobid-resources/issues/427 & https://wiki.dnb.de/pages/viewpage.action?pageId=125410060&focusedCommentId=125416192#comment-125416192.

**Comment by acka47** [comment]
As @larsgsvensson suggests [here](https://wiki.dnb.de/pages/viewpage.action?pageId=125410060&focusedCommentId=125416271#comment-125416271) we should also add a property chain to the vocab like this:

```
[ ] rdfs:subPropertyOf dct:isPartOf ;
  owl:propertyChain (
  lv:isPartOf
  lv:superordinate
  ) .
```

**Comment by fsteeg** [comment]
> As @larsgsvensson suggests here we should also add a property chain to the vocab like this: [...]

Could it make sense to reverse our current approach to avoid confusion with `dct:isPartOf`? Like:

```
"subordinate" : [ {
    "numbering" : "2",
    "isPartOf" : {
      "id" : "http://lobid.org/resources/HT002888668#!",
      "label" : "lobid Ressource"
    }
} ]

```

Also `subordinate.numbering` seems more correct than `isPartOf.numbering` for what it means.

**Comment by larsgsvensson** [comment]
In that case I think we should call it `isSubordinateOf` so that the direction of the relationship is clear (unlike e. g. `skos:broader`where at least I alway need to think three times before I use it...)
