### ISSUE TITLE
Add new properties stageDesign and choirTraining

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-vocabs#80]
Because of https://github.com/hbz/lobid-resources/issues/463 we have to add to roles to our vocabulary: "stageDesign" and "choirTraining".

**Comment by acka47** [comment]
Along with "Braille" (see https://github.com/hbz/lobid-resources/issues/827), these are neither properties nor classes but `skos:Concept`s. So lobid-vocab isn't actually the right place to add this to. I will think about a solution.

**Comment by acka47** [comment]
I think this is not used in lobid-resources anymore, see e.g. https://github.com/hbz/lobid-resources/blob/58242ea41e1489ba82e44540813d2e9523f361e3/src/main/resources/alma/fix/macros.fix#L79  Closing.
