### ISSUE TITLE
Restructure NWBib spatial classification

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#86]
Fixes part of https://github.com/hbz/nwbib/issues/452 ("Dekanate und Kirchenkreise hierarchisch unter die Diözesen bzw. Evengelische Kirche Rheinland/Westfalen sortieren").

**Comment by acka47** [comment]
As this is about entries we derive from Wikidata, I suppose we resolve this together with #85. 

To dos:

- [ ] All Kirchenkreise that according to Wikidata are in Q1380992 ("Evangelische Kirche des Rheinlands") are moved under notation 32 (see [this SPARQL query](http://tinyurl.com/y6ycd6ed))
- [ ] All Kirchenkreise that according to Wikidata are in Q1381014 ("Evangelische Kirche von Westfalen") are moved under notation 33 ([SPARQL query](http://tinyurl.com/y6rc2xoq))
- [ ] Notation 35 is removed from the classification

**Comment by acka47** [comment]
Another big task for restructuring was requested by H.F. via email on 2019-05-01:

> Was ... die Position der Verwaltungsgliederung anbelangt, so erschien es uns schon immer als weniger gute Lösung, sie in der Hauptgruppe 9 ganz hinten in der Raumsystematik anzusiedeln, also hinter den kirchlichen und historischen Gebieten. Aufgrund der Gliederung des AGS ergibt sich aber nun eine gute Gelegenheit, sie ganz nach vorn zu bringen. Beginnen doch die Schlüssel des AGS für unser Bundesland NRW mit den Ziffern 05, um in den weiteren sechs Stellen Regierungsbezirke, Kreise und Orte numerisch strukturiert abzubilden. Die Gruppe 05 soll daher in Zukunft von unserer Verwaltungsgliederung eingenommen werden.
>
> Damit dieses Konzept greifen kann, müssen wir allerdings die bislang unter 05 firmierende Gruppe "Westfalen" auf die neue Raumsystematik-Gruppe 04 umnotieren. Das alles kann natürlich nur automatisch durch Sie im hbz erfolgen. Wir denken, dass dafür auch jetzt der geeignete Zeitpunkt ist, ehe die von Ihnen geschilderten weiteren Arbeiten in Abstimmung mit der Verbundgruppe / Verbunddatenbank erfolgen.

**Comment by acka47** [comment]
Restructuring will occur in this file: https://github.com/hbz/nwbib/blob/lobid-vocabs-85/conf/non-90s-qids.json

**Comment by acka47** [comment]
With https://github.com/hbz/lobid-resources/pull/1006 we made sure that "Lippischer Wald" will be matched with the corresponding Wikidata entry. The data is now updated n lobid-resources but NWBib has to be adjusted as well, see e.g. https://nwbib.de/BT000059116 and https://nwbib.de/spatial#Q31312912.

**Comment by acka47** [comment]
Here is another reason for updating the NWBib: As reported by I.N. via email today, there are two new places that have been added by the NWBib editors:

Am 15.07.19 um 11:23 schrieb I.N.:
> uns ist aufgefallen, dass zwei neue Ortsteile (Sendschotten, Twismecke ) 
> noch nicht in der NWBib-Raumsystematik angezeigt werden.
> 
> Die Raumnotationen wurden in der HBZ-Titeldatei wie üblich im Feld 700n 
> „99 | Drolshagen-Sendschotten“ und 700n „99 | Schmallenberg-Twismecke“ 
> erfasst.

While both are missing in https://nwbib.de/spatial and Sendschotten is not shown in detail views (see e.g.  https://nwbib.de/HT020122055), the detail view for "Twismecke" strangely looks good, see https://nwbib.de/HT020127780

**Comment by acka47** [comment]
For the last step "Move Regierungsbezirke, Kreise, Gemeinden etc. under 05", we just have to add `skos:broader nwbib-spatial:N05´ to the seven Regierungsbezirke and Euregio and create a new entry `nwbib-spatial:N05` with `skos:prefLabel "Regierungsbezirke, Kreise, Orte"@de` while moving the existing `N05` to `nwbib-spatial:N04".

**Comment by fsteeg** [comment]
> [...] while moving the existing N05 to `nwbib-spatial:N04`

Hm, but there is no `nwbib-spatial:N04` (yet). Or do you mean `nwbib-spatial#n4-7`?

**Comment by acka47** [comment]
> but there is no `nwbib-spatial:N04` (yet). Or do you mean `nwbib-spatial#n4-7`?

Yes, the existing `N05` becomes `N04`:

```
nwbib-spatial:N05  a    skos:Concept ;
        skos:broader    nwbib-spatial:N0 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:notation   "05" ;
        skos:prefLabel  "Westfalen"@de ;
        foaf:focus      wd:Q8614 .
```

**Comment by fsteeg** [comment]
Should now contain everything from the original comment, except the last point, which moved to https://github.com/hbz/lobid-vocabs/issues/91:

https://raw.githubusercontent.com/hbz/lobid-vocabs/3cc2866eaa1c5475044b5532d89e65d71f79dd7c/nwbib/nwbib-spatial.ttl

**Comment by fsteeg** [comment]
For testing, I've set up usage of the new SKOS file and disabled adding other entries here:

https://test.nwbib.de/spatial

**Comment by acka47** [comment]
Looks good. +1 for deploying. I think it would only be consistent to move the Dekanate ([N37](https://test.nwbib.de/spatial#N37)) under the respective Diözese ([N36](https://test.nwbib.de/spatial#N36)) as we do with Kirchenkreise and Bistümer. However, we will aski NWBib editors before adjusting this.

**Comment by fsteeg** [comment]
>  I think it would only be consistent to move the Dekanate (N37) under the respective Diözese (N36) as we do with Kirchenkreise and Bistümer. However, we will ask NWBib editors before adjusting this.

Yes, I think that was agreed upon in the last meeting, so I think we can go ahead with that  (https://wiki1.hbz-nrw.de/display/SEM/NWBib-Raumsystematik-Treffen+2019):

> "Einstimmigkeit, dass Dekanate und Kirchenkreise hierarchisch unter die Diözesen bzw. Evengelische Kirche Rheinland/Westfalen sortiert werden"

Also, some are already sorted under Diözesen: https://test.nwbib.de/spatial#N36

We should probably wait with deploying this until that is done too.

**Comment by acka47** [comment]
I added the hierarchy for Dekanate with https://github.com/hbz/nwbib/pull/483/commits/0aee324dcef447befa55d3fa34b5f24f962a7e16.

I did this manually now but we should do this autmatically. We basically just have to use the property [P708 "Diözese"](https://www.wikidata.org/wiki/Property:P708) for obtaining hierarchical information. i used this SPARQL query to get all information I need: https://w.wiki/7FU

**Comment by fsteeg** [comment]
Deployed with latest changes:

https://raw.githubusercontent.com/hbz/lobid-vocabs/85-spatial/nwbib/nwbib-spatial.ttl
https://test.nwbib.de/spatial

As discussed, I created a new issue for the remaining TODO: https://github.com/hbz/lobid-vocabs/issues/93

**Comment by acka47** [comment]
+1 (We will have to rename the label for 36, currently "Katholische Kirche. Diözesen". Will ask NWBib editors after deployment to production what label we will use in the future.)

**Comment by fsteeg** [comment]
OK, so when you approve https://github.com/hbz/lobid-vocabs/pull/92, I'll merge the Turtle file and deploy the new setup based on that file to production (https://github.com/hbz/nwbib/pull/483)

**Comment by acka47** [comment]
Done
