### ISSUE TITLE
Move Regierungsbezirke, Kreise, Gemeinden etc. under 05

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-vocabs#91]
Moved out of #86. See details starting at https://github.com/hbz/lobid-vocabs/issues/86#issuecomment-498195821.

**Comment by acka47** [comment]
As discussed, we will have to change to notations from their current value as used in hbz01:

- 05 Westfalen -> 04 Westfalen
- 91 Euregio -> 91 :question:  (We will have to ask editors about the new notation)

**Comment by fsteeg** [comment]
Duplicate of https://github.com/hbz/lobid-vocabs/issues/93, which has more info, so closing this.
