### ISSUE TITLE
Move Regierungsbezirke, Kreise, Gemeinden etc. under 05

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-vocabs#93]
Moving to separate issue as discussed with @acka47 to unblock #86. Requires data changes.

Original description by @acka47 in https://github.com/hbz/lobid-vocabs/issues/86#issuecomment-498195821:

Another big task for restructuring was requested by H.F. via email on 2019-05-01:

> Was ... die Position der Verwaltungsgliederung anbelangt, so erschien es uns schon immer als weniger gute Lösung, sie in der Hauptgruppe 9 ganz hinten in der Raumsystematik anzusiedeln, also hinter den kirchlichen und historischen Gebieten. Aufgrund der Gliederung des AGS ergibt sich aber nun eine gute Gelegenheit, sie ganz nach vorn zu bringen. Beginnen doch die Schlüssel des AGS für unser Bundesland NRW mit den Ziffern 05, um in den weiteren sechs Stellen Regierungsbezirke, Kreise und Orte numerisch strukturiert abzubilden. Die Gruppe 05 soll daher in Zukunft von unserer Verwaltungsgliederung eingenommen werden.
>
> Damit dieses Konzept greifen kann, müssen wir allerdings die bislang unter 05 firmierende Gruppe "Westfalen" auf die neue Raumsystematik-Gruppe 04 umnotieren. Das alles kann natürlich nur automatisch durch Sie im hbz erfolgen. Wir denken, dass dafür auch jetzt der geeignete Zeitpunkt ist, ehe die von Ihnen geschilderten weiteren Arbeiten in Abstimmung mit der Verbundgruppe / Verbunddatenbank erfolgen.

H.F. also provided a "Auszugsskizze", see [Skizze_NWB-RaumSysGr.0-mit-Vw.Gliederung-gem-AKS-u.-AGS.pdf](https://github.com/hbz/lobid-vocabs/files/3247053/Skizze_NWB-RaumSysGr.0-mit-Vw.Gliederung-gem-AKS-u.-AGS.pdf):

> Die Notationen ab der Ebene der Regierungsbezirke entsprechen den amtlichen Schlüsseln, wobei es neben dem bereits genannten Amtlichen Gemeindeschlüssel (AGS) auch einen Amtlichen Kreisschlüssel (AKS)  (https://deacademic.com/dic.nsf/dewiki/71259#Aufbau) gibt. Der Kreisschlüssel ist fünfstellig, der Gemeindeschlüssel achtstellig. Beide Schlüssel finden sich auch in den Datenübersichten der Wikipedia-Artikel zu einzelnen Kreisen und Städten (vgl. z. B. Kreise Kleve und zugehörige Gemeinden).
>
> Für einige Altkreise suchen wir noch nach ggf. älteren Schlüsseln. Über die Position der Euregio stimmen sich die NWBib-Redaktionen noch ab. Einige Kreisschlüssel müssen wohl noch in Wikidata von uns ergänzt werden.

**Comment by acka47** [comment]
From https://github.com/hbz/lobid-vocabs/issues/86#issuecomment-516374311

> For the last step "Move Regierungsbezirke, Kreise, Gemeinden etc. under 05", we just have to add `skos:broader nwbib-spatial:N05` to the seven Regierungsbezirke and Euregio and create a new entry `nwbib-spatial:N05` with `skos:prefLabel "Regierungsbezirke, Kreise, Orte"@de` while moving the existing `N05` to `nwbib-spatial:N04"`.

**Comment by fsteeg** [comment]
From @acka47 in https://github.com/hbz/lobid-vocabs/issues/91#issuecomment-516734934: 

As discussed, we will have to change to notations from their current value as used in hbz01:

    05 Westfalen -> 04 Westfalen
    91 Euregio -> 91 question (We will have to ask editors about the new notation)

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/spatial

**Comment by fsteeg** [comment]
Redeployed as discussed offline: https://test.nwbib.de/spatial#N05

**Comment by acka47** [comment]
This look great. We should deploy this now.
